import random
import copy
from pathlib import Path
resultado=[]
conexiones=0

"""
This function receives the number of rows and columns and create a matrix fill with 0s.
"""
def crearMatrizNula(filas, columnas):
    matriz=[]
    temp=[]
    i=0
    j=0
    while i<filas:
        while j<columnas:
            temp+=[0]
            j+=1
        matriz+=[temp]
        j=0
        i+=1
        temp=[]
    return matriz

"""
This function check that a maze already has a starting point (2 in the matrix).
"""
def tienePuntoInicio(matriz):
    for i in range(len(matriz)):
        for j in range(len(matriz)):
            if matriz[i][j]==2:
                return True
    return False

"""
This function create randomly a starting point in the maze with a 2.
"""
def marcarPuntoInicio(matriz):
    tamano=len(matriz)
    matrizTemp=copy.deepcopy(matriz)
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    while matrizTemp[posX][posY]!=1 and matrizTemp[posX][posY]==3:
        posX= random.randint(0, tamano-1)
        posY= random.randint(0, tamano-1)
    matriz[posX][posY]=2
    return matriz

"""
This function remove the starting point in the maze, changing the 2 to 1.
"""
def desmarcarPuntoInicio(matriz):
    tamano=len(matriz)
    for i in range(tamano):
        for j in range(tamano):
            if matriz[i][j]==2:
                matriz[i][j]=1
    return matriz


#The last three functions are used in the save and load functions by changing the game mode.

"""
This function remove the 4s in the maze, that represents the solutions
It is used to remove the solutions when saving the maze
"""
def quitarCaminos(matriz, modo):
    tamano=len(matriz)
    for i in range(tamano):
        for j in range(tamano):
            if matriz[i][j]==4:
                    matriz[i][j]=1
            if modo=="manual" and matriz[i][j]==2:
                matriz[i][j]=1
    return matriz

""""
Esta función cambia un 0 aleatorio cerca del punto final por un 1 cuando hay solamente una solución del laberinto.
"""
def picarMuro(matriz, posX, posY):
    lista=[0,1,2,3]
    random.shuffle(lista)
    for temp in lista:
        if temp==0:
            if comprobarPosicionValida(len(matriz), posX-2, posY) and matriz[posX-2][posY]==1:
                matriz[posX-1][posY]=1
                if random.randint(0, 9)>7:
                    return matriz
        elif temp==1:
            if comprobarPosicionValida(len(matriz), posX+2, posY) and matriz[posX+2][posY]==1:
                matriz[posX+1][posY]=1
                if random.randint(0, 9)>7:
                    return matriz
        elif temp==2:
            if comprobarPosicionValida(len(matriz), posX, posY+2) and matriz[posX][posY+2]==1:
                matriz[posX][posY+1]=1
                if random.randint(0, 9)>7:
                    return matriz
        elif temp==3:
            if comprobarPosicionValida(len(matriz), posX, posY-2) and matriz[posX][posY-2]==1:
                matriz[posX][posY-1]=1
                if random.randint(0, 9)>7:
                    return matriz
    return matriz

"""
This function create a random maze.
modo means the mode of game, if modo=0 means the auto-game, 1 means the manual game
auto-game means that both the start point and the end point are generated by the COM
manual game means that the start point is chosen by the player and the end point is generated by the COM
"""
def crearCaminosAleatorios(tamano, modo):
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    matriz=crearMatrizNula(tamano, tamano)
    crearCaminosAleatorios_aux(matriz, posX, posY, -1)
    matriz[posX][posY]=3
    if modo:
        matriz= marcarPuntoInicio(matriz)
    if len(solucionarLaberinto(copy.deepcopy(matriz)))<2:
        matriz=picarMuro(matriz, posX, posY)
    return matriz

""""
This function create random routes in the maze.
Se selecciona aleatoriamente la direccion a la cual se movera y luego valida si se puede mover en esa direccion y 

Mover dos casillas en esa dirección, si el movimiento es válido y no ha sido llenado previamente se llena esa casilla
y la casilla intermedia( la que está entre las dos casillas) con un 1.
De forma aleatoria y sin excederse de 6 ocasiones se hacen conexiones entre caminos para generar más soluciones, esto se válida para que no se realice, si en la nueva posición no se pueden realizar más movimientos
"""
def crearCaminosAleatorios_aux(matriz, posX, posY, anterior):
    # anterior means the direction from which the function came to this position
    # 0 coming from the left, 1 coming from the right, 2 coming from above, 3 coming from below
    global conexiones
    if matriz[posX][posY] !=3:
        matriz[posX][posY]=1
    listaAux=[0, 1, 2, 3]
    random.shuffle(listaAux)
    for aux in listaAux:
        intermedioX = posX
        intermedioY = posY
        nuevaX = posX
        nuevaY= posY
        if aux == 0 and anterior!=1:
            intermedioX -= 1
            nuevaX -= 2
        elif aux == 1 and anterior!=0:
            intermedioX += 1
            nuevaX += 2
        elif aux == 2 and anterior!=3:
            intermedioY -= 1
            nuevaY -= 2
        elif aux == 3 and anterior!=2:
            intermedioY += 1
            nuevaY += 2
        if comprobarPosicionValida(len(matriz), nuevaX, nuevaY) and comprobarPosicionValida(len(matriz), intermedioX, intermedioY):
            rand=random.randint(0, 10)
            if rand<=8 or conexiones>6:
                if comprobarCero(matriz, intermedioX, intermedioY) and comprobarCero(matriz, nuevaX, nuevaY):
                    matriz[intermedioX][intermedioY]=1
                    crearCaminosAleatorios_aux(matriz, nuevaX, nuevaY, aux)
            else:
                if comprobarConexionCaminos(matriz, nuevaX, nuevaY):
                    matriz[intermedioX][intermedioY]=1
                    conexiones+=1
                    crearCaminosAleatorios_aux(matriz, nuevaX, nuevaY, aux)
                
    return False
    
"""
Esta función comprueba si en la casilla que se encuentra en la coordenada (posX, posY) hay un cero (pared).
"""
def comprobarCero(matriz, posX, posY):
    tamano=len(matriz)
    if comprobarPosicionValida(tamano, posX, posY) and matriz[posX][posY]==0:
        return True

"""
Esta función comprueba si en dos posiciones alrededor de la coordenada (posX, posY) hay un cero (pared).
"""
def comprobarConexionCaminos(matriz, posX, posY):
    if comprobarPosicionValida(len(matriz), posX-2, posY) and matriz[posX-2][posY]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX+2, posY) and matriz[posX+2][posY]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX, posY-2) and matriz[posX][posY-2]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX, posY+2) and matriz[posX][posY+2]==0:
        return True
    return False
    
"""
Esta función comprueba si la casilla que se encuentra en la coordenada (posX, posY) es valida y se encuentra dentro del laberinto.
"""
def comprobarPosicionValida(tamano, x, y):
    if x>=0 and y>=0 and x<tamano and y<tamano:
        return True
    return False

"""
Ordena las soluciones de menor a mayor cantidad de pasos para llegar a la meta (cantidad mínima de pasos).
"""
def ordenarSoluciones(soluciones):
    if len(soluciones) <= 1:
        return soluciones
    pivote = soluciones[0]
    menores = []
    mayores = []
    for i in range(1, len(soluciones)):
        solucion = soluciones[i]
        if cantCuatros(solucion) < cantCuatros(pivote):
            menores.append(solucion)
        else:
            mayores.append(solucion)
    return ordenarSoluciones(menores) + [pivote] + ordenarSoluciones(mayores)

total_pasos=[]

"""
Obtiene la lista de todos los pasos realizados para llegar a la meta.
"""
def getTotalPasos():
    global total_pasos
    t = copy.deepcopy(total_pasos)
    total_pasos = []
    return t

"""
Es la función principal del algoritmo de solución del laberinto.
"""
def solucionarLaberinto(matriz):
    global resultado, total_pasos
    total_pasos=[]
    resultado=[]
    x = 0
    y = 0
    for i in range(len(matriz)):
        for j in range(len(matriz)):
            if matriz[j][i] == 2:
                x = j
                y = i

    solucionar_aux(matriz, x, y, [])
    return resultado

"""
- Esta función busca las soluciones del laberinto, mediante backtracking, y las guarda en la variable global "resultado".
- La función recibe la matriz del laberinto, la coordenada de inicio (posX, posY), y la lista de pasos realizados hasta el momento (pasos). 
- Según las coordenadas recibidas, valida los caminos hacia donde se pueda desplazarse y cada vez que se encuentra una intersección entre
  dos o más caminos, se llama recursivamente a la misma función por cada posible camino que se pueda seguir.p
- Cada vez que se llega a la meta (4) se guarda la matriz y la lista de pasos realizados en la variable global "resultado" y "total_pasos".
"""   
def solucionar_aux(matriz, posX, posY, pasos):
    global resultado, total_pasos
    arriba, abajo, izquierda, derecha = 0, 0, 0, 0
    if posY > 0:
        arriba = matriz[posX][posY-1]
    if posY < len(matriz)-1:
        abajo = matriz[posX][posY+1]
    if posX < len(matriz)-1:
        derecha = matriz[posX+1][posY]
    if posX > 0:
        izquierda = matriz[posX-1][posY]
        
    simbolos = [arriba, abajo, izquierda, derecha]
   
    if matriz[posX][posY] != 2:
        matriz[posX][posY] = 4
    
    if 3 in simbolos:
        if matriz not in resultado:
            resultado.append(copy.deepcopy(matriz))
            total_pasos.append(copy.deepcopy(pasos))
        pasos = []
        return True
    
    
    pasos.append([posX, posY])
    if 1 not in simbolos:
        matriz[posX][posY] = 5
        
        return False
    
    if arriba == 1 or arriba == 4 and [posX, posY-1] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX, posY-1, pasos)
    if abajo == 1 or abajo == 4 and [posX, posY+1] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX, posY+1, pasos)
    if izquierda == 1 or izquierda == 4 and [posX-1, posY] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX-1, posY, pasos)
    if derecha == 1 or derecha == 4 and [posX+1, posY] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX+1, posY, pasos)


#esta función devuelve la mejor solución dentro de las solu
"""
Esta función recibe una lista de matrices y devuelve la mejor solución encontrada, buscando la que tenga la menor cantidad de pasos (4s en la matriz).
"""
def solucionOptima(listaMatrices):
    cantPasosMejorSolucion=cantCuatros(listaMatrices[0])
    mejorSolucion=listaMatrices[0]
    for matriz in listaMatrices:
        cantPasos=cantCuatros(matriz)
        if cantPasosMejorSolucion>cantPasos:
            cantPasosMejorSolucion=cantPasos
            mejorSolucion=matriz
    return mejorSolucion
        

"""
Esta función devuelve True si se encuentra la meta alrededor de la casilla que se encuentra en la coordenada (posX, posY).
"""
def comprobarMetaAlrededores(matriz, x, y):
    if comprobarPosicionValida(len(matriz), x-1, y) and matriz[x-1][y] == 3:
        return True
    elif comprobarPosicionValida(len(matriz), x+1, y) and matriz[x+1][y] == 3:
        return True
    elif comprobarPosicionValida(len(matriz), x, y-1) and matriz[x][y-1] == 3:
        return True
    elif comprobarPosicionValida(len(matriz), x, y+1) and matriz[x][y+1] == 3:
        return True
    return False

"""
Esta función devuelve la cantidad de cuatros (4) que hay en la matriz.
"""
def cantCuatros(matriz):
    resultado=0
    for i in matriz:
        for j in i:
            if j==4:
                resultado+=1
    return resultado

"""
Esta función recibe la matriz y cambia todos los 4 por 1, es decir, elimina los pasos realizados.
"""
def limpiar(matriz):
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if matriz[i][j]==4:
                matriz[i][j]=1
    return matriz

"""
Esta función recibe la matriz y devuelve la lista de coordenadas (pasos) realizados para la solucion más óptima
"""
def obtenerPasos(matriz):
    coordenada_inicio = [0, 0]
    coordenadas = []
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if matriz[i][j]==2:
                coordenada_inicio = [i, j]
    coordenadas.append(coordenada_inicio)
    n = 0
    encontrado = False
    while encontrado == False:
        
        arriba = 0
        abajo = 0
        derecha = 0
        izquierda = 0

        i = coordenada_inicio[0]
        j = coordenada_inicio[1]

        if i != 0:
            arriba = matriz[i-1][j]
        if i != len(matriz)-1:
            abajo = matriz[i+1][j]
        if j != 0:
            derecha = matriz[i][j-1]
        if j != len(matriz[0])-1:
            izquierda = matriz[i][j+1]

        if arriba == 3 or abajo == 3 or derecha == 3 or izquierda == 3 or n == 30:
            encontrado = True
        
        if arriba == 4:
            if [i-1, j] not in coordenadas:
                i-=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if abajo == 4:
            if [i+1, j] not in coordenadas:
                i+=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if derecha == 4:
            if [i, j-1] not in coordenadas:
                j-=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if izquierda == 4:
            if [i, j+1] not in coordenadas:
                j+=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  

    return coordenadas
