import random
import copy
from pathlib import Path
resultado=[]
conexiones=0
def crearMatrizNula(filas, columnas):
    matriz=[]
    temp=[]
    i=0
    j=0
    while i<filas:
        while j<columnas:
            temp+=[0]
            j+=1
        matriz+=[temp]
        j=0
        i+=1
        temp=[]
    return matriz

"""def crearCaminoAleatorio(tamano):
    matriz=crearMatrizNula(tamano, tamano)
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    
    limite = determinarTotalEspacios(tamano)
     
    while limite!=0:

        if matriz[posX][posY]==0 :
            matriz[posX][posY]=1
            limite -= 1
        aux= random.randint(0, 3)
        if aux==0 and comprobarPosicionValida(tamano, posX-1, posY):
            if comprobarAlrededores(matriz, posX-1, posY):
                posX-=1     
        elif aux==1 and comprobarPosicionValida(tamano, posX+1, posY):
            if comprobarAlrededores(matriz, posX+1, posY):
                posX+=1
        elif aux==2 and comprobarPosicionValida(tamano, posX, posY+1):
            if comprobarAlrededores(matriz, posX, posY+1):
                posY+=1
        elif aux==3 and comprobarPosicionValida(tamano, posX, posY-1):
            if comprobarAlrededores(matriz, posX, posY-1):
                posY-=1
    return matriz
"""

def determinarTotalCaminos(tamano):
    limite=1
    if tamano ==10:
        limite= random.randint(1, 2)
    elif tamano ==15:
        limite= random.randint(1, 3)
    elif tamano ==20:
        limite= random.randint(1,4)
    else:
        limite= random.randint(1, 5)
    return limite

def marcarPuntoInicio(matriz):
    tamano=len(matriz)
    matrizTemp=copy.deepcopy(matriz)
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    while matrizTemp[posX][posY]!=1 and not solucionarLaberinto(matrizTemp):
        posX= random.randint(0, tamano-1)
        posY= random.randint(0, tamano-1)
    matriz[posX][posY]=2
    return matriz
    
def crearCaminosAleatorios(tamano, modo):
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    #modo means the mode of game, if modo=0 means the auto-game, 1 means the manual game
    #auto-game means that both the start point and the end point are generated by the COM
    #manual game means that the start point is chosen by the player and the end point is generated by the COM
    matriz=crearMatrizNula(tamano, tamano)
    crearCaminoAleatorio(matriz, posX, posY, -1)
    matriz[posX][posY]=3
    if modo:
        matriz= marcarPuntoInicio(matriz)
    return matriz
    
def crearCaminoAleatorio(matriz, posX, posY, anterior):
    global conexiones
    if matriz[posX][posY] !=3:
        matriz[posX][posY]=1
    #0 que viene de izquierda, 1 que viene de derecha, 2 que viene de arriba, 3 que viene de abajo
    listaAux=[0, 1, 2, 3]
    random.shuffle(listaAux)
    for aux in listaAux:
        intermedioX = posX
        intermedioY = posY
        nuevaX = posX
        nuevaY= posY
        if aux == 0 and anterior!=1:
            intermedioX -= 1
            nuevaX -= 2
        elif aux == 1 and anterior!=0:
            intermedioX += 1
            nuevaX += 2
        elif aux == 2 and anterior!=3:
            intermedioY -= 1
            nuevaY -= 2
        elif aux == 3 and anterior!=2:
            intermedioY += 1
            nuevaY += 2
        if comprobarPosicionValida(len(matriz), nuevaX, nuevaY) and comprobarPosicionValida(len(matriz), intermedioX, intermedioY):
            rand=random.randint(0, 10)
            if rand<=8 and conexiones>6:
                if marcarCamino(matriz, intermedioX, intermedioY) and marcarCamino(matriz, nuevaX, nuevaY):
                    matriz[intermedioX][intermedioY]=1
                    crearCaminoAleatorio(matriz, nuevaX, nuevaY, aux)
            else:
                if comprobarConexionCaminos(matriz, nuevaX, nuevaY):
                    matriz[intermedioX][intermedioY]=1
                    conexiones+=1
                    crearCaminoAleatorio(matriz, nuevaX, nuevaY, aux)
                
    return False
        
def marcarCamino(matriz, posX, posY):
    tamano=len(matriz)
    if comprobarPosicionValida(tamano, posX, posY) and matriz[posX][posY]==0:
        return True
    
def comprobarConexionCaminos(matriz, posX, posY):
    if comprobarPosicionValida(len(matriz), posX-2, posY) and matriz[posX-2][posY]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX+2, posY) and matriz[posX+2][posY]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX, posY-2) and matriz[posX][posY-2]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX, posY+2) and matriz[posX][posY+2]==0:
        return True
    return False
    
    
def crearCaminoFalso(matriz, tamano, posX, posY,anterior):
    if matriz[posX][posY] == 3 or matriz[posX][posY] == 2:
        return False
    if matriz[posX][posY]==1:
        return True
    matriz[posX][posY]=1
    
    #0 que viene de izquierda, 1 que viene de derecha, 2 que viene de arriba, 3 que viene de abajo
    listaAux=[0, 1, 2, 3]
    random.shuffle(listaAux)
    for aux in listaAux:
        nuevaX = posX
        nuevaY= posY
        if aux == 0 and anterior!=1:
            nuevaX -= 1
        elif aux == 1 and anterior!=0:
            nuevaX += 1
        elif aux == 2 and anterior!=3:
            nuevaY -= 1
        elif aux == 3 and anterior!=2:
            nuevaY += 1
        if comprobarPosicionValida(tamano, nuevaX, nuevaY) and comprobarAlrededores(matriz, nuevaX, nuevaY, aux,0):
            if crearCaminoFalso(matriz, tamano, nuevaX, nuevaY, aux):
                return matriz
    matriz[posX][posY]=0
    return False

"""def crearCaminoAleatorio_aux(tamano, matriz, posX, posY, limite):

    if limite==0:
        matriz[posX][posY]=3
        return True 
    if matriz[posX][posY]!=0:
        return False
    
    matriz[posX][posY]=1
    limite -= 1
    
    #0 que viene de izquierda, 1 que viene de derecha, 2 que viene de arriba, 3 que viene de abajo
    listaAux=[0, 1, 2, 3]
    random.shuffle(listaAux)
    for aux in listaAux:
        nuevaX = posX
        nuevaY= posY
        if aux == 0:
            nuevaX -= 1
        elif aux == 1:
            nuevaX += 1
        elif aux == 2:
            nuevaY -= 1
        elif aux == 3:
            nuevaY += 1
        if comprobarPosicionValida(tamano, nuevaX, nuevaY) and comprobarAlrededores(matriz, nuevaX, nuevaY, aux):
            if crearCaminoAleatorio_aux(tamano, matriz, nuevaX, nuevaY, limite):
                return True
    #matriz[posX][posY]=0
    
    return False
    
    otra
    if anterior==0:
        return crearCaminoAleatorio_aux(tamano, matriz, posX-1, posY, limite, 1)
    elif anterior==1:
        return crearCaminoAleatorio_aux(tamano, matriz, posX+1, posY, limite, 0)
    elif anterior==2:
        return crearCaminoAleatorio_aux(tamano, matriz, posX, posY-1, limite, 3)
    else:
        return crearCaminoAleatorio_aux(tamano, matriz, posX, posY+1, limite, 2)
"""
def determinarTotalEspacios(tamano):
    if tamano ==5:
        limite= random.randint(5, 10)
    elif tamano ==10:
        limite= random.randint(15, 50)
    elif tamano ==15:
        limite= random.randint(30, 175)
    elif tamano ==20:
        limite= random.randint(320, 340)
    else:
        limite= random.randint(540, 580)
    return limite

def comprobarPosicionValida(tamano, x, y):
    if x>=0 and y>=0 and x<tamano and y<tamano:
        return True
    return False

def comprobarAlrededores(matriz, x, y, aux, modo):
    if not modo:
        if aux == 0 or aux == 1:
            if comprobarPosicionValida(len(matriz), x, y-1) and matriz[x][y-1]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x, y+1) and matriz[x][y+1]==1:
                return False
        elif aux == 2 or aux == 3:
            if comprobarPosicionValida(len(matriz), x-1, y) and matriz[x-1][y]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x+1, y) and matriz[x+1][y]==1:
                return False
    else:
        if aux == 0:
            if comprobarPosicionValida(len(matriz), x-1, y+1) and matriz[x-1][y]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x, y+1) and matriz[x][y+1]==1:    
                return False
            elif comprobarPosicionValida(len(matriz), x, y-1) and matriz[x][y-1]==1:
                return False
        elif aux == 1:
            if comprobarPosicionValida(len(matriz), x+1, y) and matriz[x+1][y]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x, y-1) and matriz[x][y-1]==1:    
                return False
            elif comprobarPosicionValida(len(matriz), x, y+1) and matriz[x][y+1]==1:
                return False
        elif aux == 2:
            if comprobarPosicionValida(len(matriz), x, y-1) and matriz[x][y-1]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x-1, y) and matriz[x-1][y]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x+1, y) and matriz[x+1][y]==1:
                return False

        else:
            if comprobarPosicionValida(len(matriz), x, y+1) and matriz[x][y+1]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x-1, y) and matriz[x-1][y]==1:
                return False
            elif comprobarPosicionValida(len(matriz), x+1, y) and matriz[x+1][y]==1:
                return False
    return True

def cantUnos(matriz):
    resultado=0
    for i in matriz:
        for j in i:
            if j==1:
                resultado+=1
    return resultado

def ordenarSoluciones(soluciones):
    if len(soluciones) <= 1:
        return soluciones
    pivote = soluciones[0]
    menores = []
    mayores = []
    for i in range(1, len(soluciones)):
        solucion = soluciones[i]
        if cantCuatros(solucion) < cantCuatros(pivote):
            menores.append(solucion)
        else:
            mayores.append(solucion)
    return ordenarSoluciones(menores) + [pivote] + ordenarSoluciones(mayores)

total_pasos=[]

def getTotalPasos():
    global total_pasos
    t = copy.deepcopy(total_pasos)
    total_pasos = []
    return t

"""def solucionarLaberinto(matriz, inicioX, inicioY, finX, finY):
    global total_pasos
    soluciones=[]
    cantPasosMejorMatriz=1000
    tamano=len(matriz)
    intentos=10
    if tamano==10:
        intentos=20
    elif tamano==15:
        intentos=50
    elif tamano==20:
        intentos=100
    elif tamano==25:
        intentos=150
    for i in range(intentos): 
        matrizTemporal=copy.deepcopy(matriz)
        pasos=copy.deepcopy([])
        if solucionarLaberinto_aux(tamano, matrizTemporal, inicioX, inicioY, finX, finY, inicioX, inicioY, 0, cantPasosMejorMatriz, pasos):
            if matrizTemporal not in soluciones:
                soluciones+=[matrizTemporal]
                total_pasos+=[pasos]
    if soluciones==[]:
        return -1
    print(total_pasos)
    return soluciones
"""

"""

def solucionarLaberinto(matriz, inicioX, inicioY, finX, finY):
    global total_pasos
    tamano=len(matriz)
    global soluciones
    soluciones=[]
    total_pasos=[]
    limite=15
    if tamano==10:
        limite=25
    elif tamano==15:
        limite=30
    elif tamano==20:
        limite=35
    elif tamano==25:
        limite=40
    solucionarLaberinto_aux(tamano, matriz, inicioX, inicioY, finX, finY, inicioX, inicioY, 0, limite, [], None, True)
    if soluciones==[]:
        return -1
    return soluciones

def solucionarLaberinto_aux(tamano, matriz, inicioX, inicioY, finX, finY, posX, posY, cuatros, limite, pasos, anterior, comprobar):
    global soluciones, total_pasos
    if posX == finX and posY == finY:
        if matriz not in soluciones:
            soluciones.append(copy.deepcopy(matriz))
            total_pasos.append(copy.deepcopy(pasos))
        pasos = []
        return False  # Para que siga buscando más soluciones

    temp = matriz[posX][posY]
    if len(pasos) >= limite:
        return False
    if temp != 1 and temp!=2: 
            return False
    if temp==2 and anterior!=None:
        comprobar=False

    if temp != 2 and temp != 5:
        matriz[posX][posY] = 4
        cuatros += 1
        pasos.append([posX, posY])

    listaAux = [0, 1, 2, 3]
    #random.shuffle(listaAux)
    for aux in listaAux:
        nuevaX = posX
        nuevaY = posY
        if aux == 0:
            nuevaX -= 1
        elif aux == 1:
            nuevaX += 1
        elif aux == 2:
            nuevaY -= 1
        elif aux == 3:
            nuevaY += 1
        if comprobarPosicionValida(tamano, nuevaX, nuevaY) and comprobar:
            if solucionarLaberinto_aux(tamano, copy.deepcopy(matriz), inicioX, inicioY, finX, finY, nuevaX, nuevaY, cuatros, limite, pasos, aux, comprobar):
                pass  # Ya no salimos del ciclo aquí

    if temp != 2:
        matriz[posX][posY] = 5
        if pasos:
            pasos.pop()

    return False  # Nunca se detiene al encontrar una solución, se exploran todas
"""

def solucionarLaberinto(matriz):
    global resultado, total_pasos
    total_pasos=[]
    resultado=[]
    x = 0
    y = 0
    for i in range(len(matriz)):
        for j in range(len(matriz)):
            if matriz[j][i] == 2:
                x = j
                y = i
    solucionar_aux(matriz, x, y, [])
    return resultado
            
def solucionar_aux(matriz, posX, posY, pasos):
    global resultado, total_pasos
    arriba, abajo, izquierda, derecha = 0, 0, 0, 0
    if posY > 0:
        arriba = matriz[posX][posY-1]
    if posY < len(matriz)-1:
        abajo = matriz[posX][posY+1]
    if posX < len(matriz)-1:
        derecha = matriz[posX+1][posY]
    if posX > 0:
        izquierda = matriz[posX-1][posY]
        
    simbolos = [arriba, abajo, izquierda, derecha]
   
    if matriz[posX][posY] != 2:
        matriz[posX][posY] = 4
    
    if 3 in simbolos:
        if matriz not in resultado:
            resultado.append(copy.deepcopy(matriz))
            total_pasos.append(copy.deepcopy(pasos))
        pasos = []
        return True
    
    #pasos = copy.deepcopy(pasos)
    pasos.append([posX, posY])
    if 1 not in simbolos:
        matriz[posX][posY] = 5
        #if pasos:
        #    pasos.pop()
        return False
    
    if arriba == 1:
        solucionar_aux(copy.deepcopy(matriz), posX, posY-1, pasos)
    if abajo == 1:
        solucionar_aux(copy.deepcopy(matriz), posX, posY+1, pasos)
    if izquierda == 1:
        solucionar_aux(copy.deepcopy(matriz), posX-1, posY, pasos)
    if derecha == 1:
        solucionar_aux(copy.deepcopy(matriz), posX+1, posY, pasos)



def solucionOptima(listaMatrices):
    cantPasosMejorSolucion=cantCuatros(listaMatrices[0])
    mejorSolucion=listaMatrices[0]
    for matriz in listaMatrices:
        cantPasos=cantCuatros(matriz)
        if cantPasosMejorSolucion>cantPasos:
            cantPasosMejorSolucion=cantPasos
            mejorSolucion=matriz
    return mejorSolucion
        
def comprobarMeta(matriz, posX, posY):
    tamano=len(matriz)
    if comprobarPosicionValida(tamano, posX-1, posY) and matriz[posX-1][posY] == 3:
        return 0
    elif comprobarPosicionValida(tamano, posX+1, posY) and matriz[posX+1][posY] == 3:
        return 1
    elif comprobarPosicionValida(tamano, posX, posY-1) and matriz[posX][posY-1] == 3:
        return 2
    elif comprobarPosicionValida(tamano, posX, posY+1) and matriz[posX][posY+1] == 3:
        return 3
    return -1

def cantCuatros(matriz):
    resultado=0
    for i in matriz:
        for j in i:
            if j==4:
                resultado+=1
    return resultado

def limpiar(matriz):
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if matriz[i][j]==4:
                matriz[i][j]=1
    return matriz

def obtenerPasos(matriz):
    coordenada_inicio = [0, 0]
    coordenada_final = [0, 0]
    coordenadas = []
    visitadas = []
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if matriz[i][j]==2:
                coordenada_inicio = [i, j]
            elif matriz[i][j]==3:
                coordenada_final = [i, j]

    n = 0
    encontrado = False
    while encontrado == False:
        
        arriba = 0
        abajo = 0
        derecha = 0
        izquierda = 0

        i = coordenada_inicio[0]
        j = coordenada_inicio[1]

        if i != 0:
            arriba = matriz[i-1][j]
        if i != len(matriz)-1:
            abajo = matriz[i+1][j]
        if j != 0:
            derecha = matriz[i][j-1]
        if j != len(matriz[0])-1:
            izquierda = matriz[i][j+1]

        """
        print("coordenada", i, j)
        print("arriba:", arriba)
        print("abajo:", abajo)
        print("derecha:", derecha)
        print("izquierda:", izquierda)
        print("\n")
        """

        if arriba == 3 or abajo == 3 or derecha == 3 or izquierda == 3 or n == 30:
            encontrado = True
        
        if arriba == 4:
            if [i-1, j] not in coordenadas:
                i-=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if abajo == 4:
            if [i+1, j] not in coordenadas:
                i+=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if derecha == 4:
            if [i, j-1] not in coordenadas:
                j-=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if izquierda == 4:
            if [i, j+1] not in coordenadas:
                j+=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  

    return coordenadas
        
matriz = [
        [2, 4, 4, 4, 0],
        [1, 1, 0, 4, 0],
        [1, 1, 1, 4, 0],
        [1, 0, 1, 1, 0],
        [1, 1, 1, 1, 3],
    ]

print(limpiar(matriz))

#print(solucionarLaberinto(matriz, 0, 0, 4, 4))




"""
cantidadPasos = cantCuatros(matrizTemporal)
            print(cantidadPasos)
            if cantidadPasos < cantPasosMejorMatriz and cantidadPasos > 0:
                cantPasosMejorMatriz = cantidadPasos
                mejorSolucion = matrizTemporal
                
logica para obtener el mejor camino

"""


