import random
import copy
from pathlib import Path

resultado=[]
total_pasos=[]
conexiones=0

"""
This function receives the number of rows and columns and create a matrix fill with 0s.
"""
def crearMatrizNula(filas, columnas):
    matriz=[]
    temp=[]
    i=0
    j=0
    while i<filas:
        while j<columnas:
            temp+=[0]
            j+=1
        matriz+=[temp]
        j=0
        i+=1
        temp=[]
    return matriz

"""
This function check that a maze already has a starting point (2 in the matrix).
"""
def tienePuntoInicio(matriz):
    for i in range(len(matriz)):
        for j in range(len(matriz)):
            if matriz[i][j]==2:
                return True
    return False

"""
This function create randomly a starting point in the maze with a 2.
"""
def marcarPuntoInicio(matriz):
    tamano=len(matriz)
    matrizTemp=copy.deepcopy(matriz)
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    while matrizTemp[posX][posY]!=1 and matrizTemp[posX][posY]==3:
        posX= random.randint(0, tamano-1)
        posY= random.randint(0, tamano-1)
    matriz[posX][posY]=2
    return matriz

"""
This function remove the starting point in the maze, changing the 2 to 1.
"""
def desmarcarPuntoInicio(matriz):
    tamano=len(matriz)
    for i in range(tamano):
        for j in range(tamano):
            if matriz[i][j]==2:
                matriz[i][j]=1
    return matriz


#The last three functions are used in the save and load functions by changing the game mode.

"""
This function remove the 4s in the maze, that represents the solutions
It is used to remove the solutions when saving the maze
"""
def quitarCaminos(matriz, modo):
    tamano=len(matriz)
    for i in range(tamano):
        for j in range(tamano):
            if matriz[i][j]==4:
                    matriz[i][j]=1
            if modo=="manual" and matriz[i][j]==2:
                matriz[i][j]=1
    return matriz

""""
This function changes a random 0 near the end point to a 1 when there is only one solution to the maze.
"""
def picarMuro(matriz, posX, posY):
    lista=[0,1,2,3]
    random.shuffle(lista)
    for temp in lista:
        if temp==0:
            if comprobarPosicionValida(len(matriz), posX-2, posY) and matriz[posX-2][posY]==1:
                matriz[posX-1][posY]=1
                if random.randint(0, 9)>7:
                    return matriz
        elif temp==1:
            if comprobarPosicionValida(len(matriz), posX+2, posY) and matriz[posX+2][posY]==1:
                matriz[posX+1][posY]=1
                if random.randint(0, 9)>7:
                    return matriz
        elif temp==2:
            if comprobarPosicionValida(len(matriz), posX, posY+2) and matriz[posX][posY+2]==1:
                matriz[posX][posY+1]=1
                if random.randint(0, 9)>7:
                    return matriz
        elif temp==3:
            if comprobarPosicionValida(len(matriz), posX, posY-2) and matriz[posX][posY-2]==1:
                matriz[posX][posY-1]=1
                if random.randint(0, 9)>7:
                    return matriz
    return matriz

"""
This function create a random maze.
modo means the mode of game, if modo=0 means the auto-game, 1 means the manual game
auto-game means that both the start point and the end point are generated by the COM
manual game means that the start point is chosen by the player and the end point is generated by the COM
"""
def crearCaminosAleatorios(tamano, modo):
    posX= random.randint(0, tamano-1)
    posY= random.randint(0, tamano-1)
    matriz=crearMatrizNula(tamano, tamano)
    crearCaminosAleatorios_aux(matriz, posX, posY, -1)
    matriz[posX][posY]=3
    if modo:
        matriz= marcarPuntoInicio(matriz)
    if len(solucionarLaberinto(copy.deepcopy(matriz)))<2:
        matriz=picarMuro(matriz, posX, posY)
    return matriz

""""
This function create random routes in the maze.
The direction in which it will move is randomly selected and then it is validated if it can move two squares in that direction, 
if the movement is valid and has not been previously filled, 
that space is filled and the intermediate space (the one between the two spaces) with a 1. 
Randomly and without exceeding 6 occasions, connections are made between routes to generate more solutions, 
this is validated so that it is not done, if in the new position no more movements can be made
"""
def crearCaminosAleatorios_aux(matriz, posX, posY, anterior):
    # anterior means the direction from which the function came to this position
    # 0 coming from the left, 1 coming from the right, 2 coming from above, 3 coming from below
    global conexiones
    if matriz[posX][posY] !=3:
        matriz[posX][posY]=1
    listaAux=[0, 1, 2, 3]
    random.shuffle(listaAux)
    for aux in listaAux:
        intermedioX = posX
        intermedioY = posY
        nuevaX = posX
        nuevaY= posY
        if aux == 0 and anterior!=1:
            intermedioX -= 1
            nuevaX -= 2
        elif aux == 1 and anterior!=0:
            intermedioX += 1
            nuevaX += 2
        elif aux == 2 and anterior!=3:
            intermedioY -= 1
            nuevaY -= 2
        elif aux == 3 and anterior!=2:
            intermedioY += 1
            nuevaY += 2
        if comprobarPosicionValida(len(matriz), nuevaX, nuevaY) and comprobarPosicionValida(len(matriz), intermedioX, intermedioY):
            rand=random.randint(0, 10)
            if rand<=8 or conexiones>6:
                if comprobarCero(matriz, intermedioX, intermedioY) and comprobarCero(matriz, nuevaX, nuevaY):
                    matriz[intermedioX][intermedioY]=1
                    crearCaminosAleatorios_aux(matriz, nuevaX, nuevaY, aux)
            else:
                if comprobarConexionCaminos(matriz, nuevaX, nuevaY):
                    matriz[intermedioX][intermedioY]=1
                    conexiones+=1
                    crearCaminosAleatorios_aux(matriz, nuevaX, nuevaY, aux)
                
    return False
    
"""
This function checks if there is a 0 (wall) in the box located at the coordinate (posX, posY).
"""
def comprobarCero(matriz, posX, posY):
    tamano=len(matriz)
    if comprobarPosicionValida(tamano, posX, posY) and matriz[posX][posY]==0:
        return True

"""
This function checks if there is a zero (wall) in the four positions around the coordinate (posX, posY), moving twice.
"""
def comprobarConexionCaminos(matriz, posX, posY):
    if comprobarPosicionValida(len(matriz), posX-2, posY) and matriz[posX-2][posY]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX+2, posY) and matriz[posX+2][posY]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX, posY-2) and matriz[posX][posY-2]==0:
        return True
    elif comprobarPosicionValida(len(matriz), posX, posY+2) and matriz[posX][posY+2]==0:
        return True
    return False
    
"""
This function checks if the space located at the coordinate (posX, posY) is valid and is inside the maze.
"""
def comprobarPosicionValida(tamano, x, y):
    if x>=0 and y>=0 and x<tamano and y<tamano:
        return True
    return False

"""
Order the solutions from least to greatest number of steps to reach the finish (minimum number of steps).
"""
def ordenarSoluciones(soluciones):
    if len(soluciones) <= 1:
        return soluciones
    pivote = soluciones[0]
    menores = []
    mayores = []
    for i in range(1, len(soluciones)):
        solucion = soluciones[i]
        if cantCuatros(solucion) < cantCuatros(pivote):
            menores.append(solucion)
        else:
            mayores.append(solucion)
    return ordenarSoluciones(menores) + [pivote] + ordenarSoluciones(mayores)

"""
Gets the list of all steps taken to reach the finish.
"""
def getTotalPasos():
    global total_pasos
    t = copy.deepcopy(total_pasos)
    total_pasos = []
    return t

"""
Is the main function of the maze solution algorithm.
"""
def solucionarLaberinto(matriz):
    global resultado, total_pasos
    total_pasos=[]
    resultado=[]
    x = 0
    y = 0
    for i in range(len(matriz)):
        for j in range(len(matriz)):
            if matriz[j][i] == 2:
                x = j
                y = i

    solucionar_aux(matriz, x, y, [])
    return resultado

"""
This function searches for solutions to the maze using backtracking and saves them in the global variable "resultado".
- The function receives the maze matrix, the starting coordinates (posX, posY), and the list of steps taken so far (pasos).
- Based on the received coordinates, it validates the routes that can be navigated, 
  and each time an intersection is found between two or more routes, the same function is called recursively for each possible path that can be followed.
- Each time the finish is reached (4), the matrix and the list of steps taken are saved in the global variables "resultado" and "total_pasos".
"""   
def solucionar_aux(matriz, posX, posY, pasos):
    global resultado, total_pasos
    arriba, abajo, izquierda, derecha = 0, 0, 0, 0
    if posY > 0:
        arriba = matriz[posX][posY-1]
    if posY < len(matriz)-1:
        abajo = matriz[posX][posY+1]
    if posX < len(matriz)-1:
        derecha = matriz[posX+1][posY]
    if posX > 0:
        izquierda = matriz[posX-1][posY]
        
    simbolos = [arriba, abajo, izquierda, derecha]
   
    if matriz[posX][posY] != 2:
        matriz[posX][posY] = 4
    
    if 3 in simbolos:
        if matriz not in resultado:
            resultado.append(copy.deepcopy(matriz))
            total_pasos.append(copy.deepcopy(pasos))
        pasos = []
        return True
    
    pasos.append([posX, posY])
    if 1 not in simbolos:
        matriz[posX][posY] = 5
        
        return False
    
    if arriba == 1 or arriba == 4 and [posX, posY-1] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX, posY-1, pasos)
    if abajo == 1 or abajo == 4 and [posX, posY+1] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX, posY+1, pasos)
    if izquierda == 1 or izquierda == 4 and [posX-1, posY] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX-1, posY, pasos)
    if derecha == 1 or derecha == 4 and [posX+1, posY] not in pasos:
        solucionar_aux(copy.deepcopy(matriz), posX+1, posY, pasos)


#esta función devuelve la mejor solución dentro de las solu
"""
This function receives a list of matrices and returns the best solution found, looking for the one with the fewest steps (4s in the matrix).
"""
def solucionOptima(listaMatrices):
    cantPasosMejorSolucion=cantCuatros(listaMatrices[0])
    mejorSolucion=listaMatrices[0]
    for matriz in listaMatrices:
        cantPasos=cantCuatros(matriz)
        if cantPasosMejorSolucion>cantPasos:
            cantPasosMejorSolucion=cantPasos
            mejorSolucion=matriz
    return mejorSolucion
        
"""
This function returns True if the finish is found around the square located at the coordinate (posX, posY).
"""
def comprobarMetaAlrededores(matriz, x, y):
    if comprobarPosicionValida(len(matriz), x-1, y) and matriz[x-1][y] == 3:
        return True
    elif comprobarPosicionValida(len(matriz), x+1, y) and matriz[x+1][y] == 3:
        return True
    elif comprobarPosicionValida(len(matriz), x, y-1) and matriz[x][y-1] == 3:
        return True
    elif comprobarPosicionValida(len(matriz), x, y+1) and matriz[x][y+1] == 3:
        return True
    return False

"""
This function returns the number of fours (4) in the array.
"""
def cantCuatros(matriz):
    resultado=0
    for i in matriz:
        for j in i:
            if j==4:
                resultado+=1
    return resultado

"""
This function receives the matrix and changes all 4 to 1, that is, it eliminates the steps performed.
"""
def limpiar(matriz):
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if matriz[i][j]==4:
                matriz[i][j]=1
    return matriz

"""
This function receives the matrix and returns the list of coordinates (steps) taken for the most optimal solution.
"""
def obtenerPasos(matriz):
    coordenada_inicio = [0, 0]
    coordenadas = []
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            if matriz[i][j]==2:
                coordenada_inicio = [i, j]
    coordenadas.append(coordenada_inicio)
    n = 0
    encontrado = False
    while encontrado == False:
        
        arriba = 0
        abajo = 0
        derecha = 0
        izquierda = 0

        i = coordenada_inicio[0]
        j = coordenada_inicio[1]

        if i != 0:
            arriba = matriz[i-1][j]
        if i != len(matriz)-1:
            abajo = matriz[i+1][j]
        if j != 0:
            derecha = matriz[i][j-1]
        if j != len(matriz[0])-1:
            izquierda = matriz[i][j+1]

        if arriba == 3 or abajo == 3 or derecha == 3 or izquierda == 3 or n == 30:
            encontrado = True
        
        if arriba == 4:
            if [i-1, j] not in coordenadas:
                i-=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if abajo == 4:
            if [i+1, j] not in coordenadas:
                i+=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if derecha == 4:
            if [i, j-1] not in coordenadas:
                j-=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  
        if izquierda == 4:
            if [i, j+1] not in coordenadas:
                j+=1
                coordenada_inicio = [i, j]
                coordenadas.append([i, j])
                continue  

    return coordenadas
